-- ============================================================
-- Painel Admin — catálogo gerido pelo banco (fonte única)
-- Adiciona: numero estável em produtos, papel de admin (tabela admins +
-- is_admin()), policies de escrita (produtos/categorias) e de storage.
-- Idempotente: pode rodar mais de uma vez sem erro.
-- ============================================================

-- ------------------------------------------------------------
-- 1) 'numero' estável em produtos (o front usa id numérico)
--    Preenche as linhas existentes na ordem de inserção e passa a
--    autoincrementar para novos produtos.
-- ------------------------------------------------------------
alter table public.produtos
  add column if not exists numero int generated by default as identity;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'produtos_numero_key'
  ) then
    alter table public.produtos add constraint produtos_numero_key unique (numero);
  end if;
end $$;

-- authenticated precisa usar a sequence do identity ao inserir (RLS ainda gita).
do $$
begin
  execute format(
    'grant usage, select on sequence %s to authenticated',
    pg_get_serial_sequence('public.produtos', 'numero')
  );
end $$;

-- ------------------------------------------------------------
-- 2) Papel de admin
--    Tabela sem policy de escrita => ninguém vira admin pelo cliente.
--    Só SQL/backend (service_role) insere. O usuário só enxerga o próprio registro.
-- ------------------------------------------------------------
create table if not exists public.admins (
  user_id   uuid primary key references auth.users(id) on delete cascade,
  criado_em timestamptz not null default now()
);
alter table public.admins enable row level security;

drop policy if exists "admin ve o proprio registro" on public.admins;
create policy "admin ve o proprio registro"
  on public.admins for select using (auth.uid() = user_id);

grant select on public.admins to authenticated;

-- Helper: quem chama é admin? SECURITY DEFINER lê admins sem recursão de RLS.
create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;
grant execute on function public.is_admin() to authenticated, anon;

-- ------------------------------------------------------------
-- 3) Policies de escrita no catálogo (só admin). Leitura pública continua.
-- ------------------------------------------------------------
drop policy if exists "produtos admin select tudo" on public.produtos;
create policy "produtos admin select tudo"
  on public.produtos for select using (public.is_admin());

drop policy if exists "produtos admin insert" on public.produtos;
create policy "produtos admin insert"
  on public.produtos for insert with check (public.is_admin());

drop policy if exists "produtos admin update" on public.produtos;
create policy "produtos admin update"
  on public.produtos for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "produtos admin delete" on public.produtos;
create policy "produtos admin delete"
  on public.produtos for delete using (public.is_admin());

drop policy if exists "categorias admin insert" on public.categorias;
create policy "categorias admin insert"
  on public.categorias for insert with check (public.is_admin());

drop policy if exists "categorias admin update" on public.categorias;
create policy "categorias admin update"
  on public.categorias for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "categorias admin delete" on public.categorias;
create policy "categorias admin delete"
  on public.categorias for delete using (public.is_admin());

grant insert, update, delete on public.produtos   to authenticated;
grant insert, update, delete on public.categorias to authenticated;

-- ------------------------------------------------------------
-- 4) Storage: admin gerencia fotos (público) e arquivos entregáveis (privado).
--    Leitura pública de fotos e leitura de 'arquivos' via Edge Function
--    (service_role) continuam como antes.
-- ------------------------------------------------------------
drop policy if exists "fotos admin escreve"  on storage.objects;
create policy "fotos admin escreve"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'produtos-fotos' and public.is_admin());

drop policy if exists "fotos admin atualiza" on storage.objects;
create policy "fotos admin atualiza"
  on storage.objects for update to authenticated
  using (bucket_id = 'produtos-fotos' and public.is_admin());

drop policy if exists "fotos admin remove"   on storage.objects;
create policy "fotos admin remove"
  on storage.objects for delete to authenticated
  using (bucket_id = 'produtos-fotos' and public.is_admin());

drop policy if exists "arquivos admin le"      on storage.objects;
create policy "arquivos admin le"
  on storage.objects for select to authenticated
  using (bucket_id = 'arquivos' and public.is_admin());

drop policy if exists "arquivos admin escreve" on storage.objects;
create policy "arquivos admin escreve"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'arquivos' and public.is_admin());

drop policy if exists "arquivos admin atualiza" on storage.objects;
create policy "arquivos admin atualiza"
  on storage.objects for update to authenticated
  using (bucket_id = 'arquivos' and public.is_admin());

drop policy if exists "arquivos admin remove"  on storage.objects;
create policy "arquivos admin remove"
  on storage.objects for delete to authenticated
  using (bucket_id = 'arquivos' and public.is_admin());

-- ------------------------------------------------------------
-- 5) Define o dono da loja como admin.
-- ------------------------------------------------------------
insert into public.admins (user_id)
select id from auth.users where email = 'jmas5672@gmail.com'
on conflict do nothing;
